# Generated by Django 2.1.7 on 2019-05-14 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='type',
            new_name='article_type',
        ),
    ]
