# Generated by Django 2.1.7 on 2019-05-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20190514_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletype',
            name='caption',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='category',
            name='caption',
            field=models.CharField(max_length=32),
        ),
    ]
